app/Http/Controllers/Admin/CouponController.php
resources/views/admin/banner/index.blade.php
resources/views/admin/coupons/add.blade.php
resources/views/admin/coupons/index.blade.php

BC-151 [Task][Admin][Order] Page Coupons (Add)

BC-151 [Task][Admin][Order] Page Coupons (Add)

---

app/Http/Controllers/Admin/CouponController.php
resources/views/admin/banner/edit.blade.php
resources/views/admin/coupons/edit.blade.php

BC-152 [Task][Admin][Coupon] Page Coupons (Edit)

BC-152 [Task][Admin][Coupon] Page Coupons (Edit)

---

app/Http/Controllers/Admin/CouponController.php
resources/views/admin/banner/edit.blade.php
resources/views/admin/coupons/edit.blade.php

BC-153 [Task][Admin][Coupon] Page Coupons (Delete)

BC-153 [Task][Admin][Coupon] Page Coupons (Delete)

---

app/Models/Courier.php
database/migrations/2022_06_07_141313_create_couriers_table.php

BC-146 [Task][Admin][Master] Page Courier DB

BC-146 [Task][Admin][Master] Page Courier DB

---

app/Http/Controllers/Admin/CourierController.php
app/Models/Courier.php
database/migrations/2022_06_07_141313_create_couriers_table.php
resources/views/admin/couriers/index.blade.php
resources/views/layouts/app-admin-sidebar.blade.php
routes/admin.php

BC-123 [Task][Admin][Master] Page Courier (List)

BC-123 [Task][Admin][Master] Page Courier (List)

---

app/Http/Controllers/Admin/CourierController.php
composer.json
composer.lock
config/app.php
resources/views/admin/couriers/add.blade.php
resources/views/admin/couriers/index.blade.php

BC-124 [Task][Admin][Master] Page Courier (Add)

BC-124 [Task][Admin][Master] Page Courier (Add)

---

app/Http/Controllers/Admin/CourierController.php
app/Models/Courier.php
database/migrations/2022_06_07_141313_create_couriers_table.php
resources/views/admin/couriers/edit.blade.php
resources/views/admin/couriers/index.blade.php

BC-169 [Task][Admin][Master] Page Courier Improvement Add Field Email, Password. on form (Add/Edit) & List Table

BC-169 [Task][Admin][Master] Page Courier Improvement Add Field Email, Password. on form (Add/Edit) & List Table

---

app/Http/Controllers/Admin/CourierController.php
resources/views/admin/couriers/edit.blade.php
resources/views/admin/couriers/index.blade.php

BC-125 [Task][Admin][Master] Page Courier (Edit)

BC-125 [Task][Admin][Master] Page Courier (Edit)

---

app/Http/Controllers/Merchant/BannerController.php
resources/views/merchant/banner/add.blade.php
resources/views/merchant/banner/index.blade.php
routes/merchant.php

BC-171 [Task][Merchant][Marketing] Page Banner (Add)

BC-171 [Task][Merchant][Marketing] Page Banner (Add)

---

app/Http/Controllers/Merchant/BannerController.php
resources/views/merchant/banner/edit.blade.php
resources/views/merchant/banner/index.blade.php
routes/merchant.php

BC-172 [Task][Merchant][Marketing] Page Banner (Edit)

BC-172 [Task][Merchant][Marketing] Page Banner (Edit)

---

app/Http/Controllers/Merchant/BannerController.php
resources/views/merchant/banner/index.blade.php
routes/merchant.php

BC-173 [Task][Merchant][Marketing] Page Banner (Delete)

BC-173 [Task][Merchant][Marketing] Page Banner (Delete)

---

app/Http/Controllers/Merchant/CouponController.php
resources/views/layouts/app-merchant-sidebar.blade.php
resources/views/merchant/coupon/index.blade.php
routes/merchant.php

BC-178 [Task][Merchant][Marketing] Page Coupon (List)

BC-178 [Task][Merchant][Marketing] Page Coupon (List)

---

app/Http/Controllers/Merchant/CouponController.php
resources/views/layouts/app-merchant-sidebar.blade.php
resources/views/merchant/coupon/add.blade.php
resources/views/merchant/coupon/index.blade.php
routes/merchant.php

BC-175 [Task][Merchant][Marketing] Page Coupon (Add)

BC-175 [Task][Merchant][Marketing] Page Coupon (Add)

---

app/Http/Controllers/Merchant/CouponController.php
resources/views/layouts/app-merchant-sidebar.blade.php
resources/views/merchant/coupon/add.blade.php
resources/views/merchant/coupon/edit.blade.php
resources/views/merchant/coupon/index.blade.php
routes/merchant.php

BC-176 [Task][Merchant][Marketing] Page Coupon (Edit)

BC-176 [Task][Merchant][Marketing] Page Coupon (Edit)

---

app/Http/Controllers/Merchant/CouponController.php
resources/views/layouts/app-merchant-sidebar.blade.php
resources/views/merchant/coupon/add.blade.php
resources/views/merchant/coupon/edit.blade.php
resources/views/merchant/coupon/index.blade.php
routes/merchant.php

BC-177 [Task][Merchant][Marketing] Page Coupon (Delete)

BC-177 [Task][Merchant][Marketing] Page Coupon (Delete)

---

app/Models/Tac.php
database/migrations/2022_06_21_021816_create_tacs_table.php

BC-189 [Task][Admin][Business] Terms And Condition (TAC)  DB

BC-189 [Task][Admin][Business] Terms And Condition (TAC)  DB

---

app/Http/Controllers/Admin/TACController.php
app/Models/Tac.php
database/migrations/2022_06_21_021816_create_tacs_table.php
resources/views/admin/tac/add.blade.php
resources/views/admin/tac/index.blade.php
resources/views/layouts/app-admin-sidebar.blade.php
routes/admin.php

BC-191 [Task][Admin][Business] Page Terms And Condition (TAC)  (Add)

BC-191 [Task][Admin][Business] Page Terms And Condition (TAC)  (Add)

---

app/Http/Controllers/Admin/TACController.php
resources/views/admin/tac/add.blade.php
resources/views/admin/tac/edit.blade.php
resources/views/admin/tac/index.blade.php
resources/views/layouts/app-admin-sidebar.blade.php
routes/admin.php

BC-192 [Task][Admin][Business] Page Terms And Condition (TAC)  (Edit)

BC-192 [Task][Admin][Business] Page Terms And Condition (TAC)  (Edit)

---

app/Http/Controllers/Admin/TACController.php
resources/views/admin/banner/edit.blade.php
resources/views/admin/coupons/add.blade.php
resources/views/admin/coupons/edit.blade.php
resources/views/admin/coupons/index.blade.php
resources/views/admin/couriers/add.blade.php
resources/views/admin/couriers/edit.blade.php
resources/views/admin/couriers/index.blade.php
resources/views/admin/tac/add.blade.php
resources/views/admin/tac/edit.blade.php
resources/views/admin/tac/index.blade.php
routes/admin.php

BC-193 [Task][Admin][Business] Page Terms And Condition (TAC)  (Delete)

BC-193 [Task][Admin][Business] Page Terms And Condition (TAC)  (Delete)

---

app/Http/Controllers/Admin/PrivacyController.php
app/Models/PrivacyPolicy.php
database/migrations/2022_06_23_015806_create_privacy_policies_table.php
resources/views/admin/privacy/index.blade.php
resources/views/layouts/app-admin-sidebar.blade.php
routes/admin.php

BC-199 [Task][Admin][Business] Page Privacy Policy (List)

BC-199 [Task][Admin][Business] Page Privacy Policy (List)

---

app/Http/Controllers/Admin/PrivacyController.php
app/Models/PrivacyPolicy.php
database/migrations/2022_06_23_015806_create_privacy_policies_table.php
resources/views/admin/privacy/add.blade.php
resources/views/admin/privacy/index.blade.php
resources/views/admin/tac/add.blade.php
resources/views/layouts/app-admin-sidebar.blade.php
routes/admin.php

BC-200 [Task][Admin][Business] Page Privacy Policy (Add)

BC-200 [Task][Admin][Business] Page Privacy Policy (Add)

---

app/Http/Controllers/Admin/PrivacyController.php
app/Models/PrivacyPolicy.php
database/migrations/2022_06_23_015806_create_privacy_policies_table.php
resources/views/admin/privacy/add.blade.php
resources/views/admin/privacy/edit.blade.php
resources/views/admin/privacy/index.blade.php
resources/views/admin/tac/add.blade.php
resources/views/layouts/app-admin-sidebar.blade.php
routes/admin.php

BC-201 [Task][Admin][Business] Page Privacy Policy (Edit)

BC-201 [Task][Admin][Business] Page Privacy Policy (Edit)

---

app/Http/Controllers/Admin/PrivacyController.php
app/Models/Faq.php
database/migrations/2022_06_08_004222_create_faqs_table.php
resources/views/admin/privacy/add.blade.php
resources/views/admin/privacy/edit.blade.php
resources/views/admin/privacy/index.blade.php
resources/views/admin/tac/add.blade.php
routes/admin.php

BC-184 [Task][Admin][Business] Frequent Ask Question (FAQ) DB

BC-184 [Task][Admin][Business] Frequent Ask Question (FAQ) DB

---

app/Http/Controllers/Admin/FaqController.php
app/Http/Controllers/Admin/PrivacyController.php
app/Models/Faq.php
database/migrations/2022_06_08_004222_create_faqs_table.php
resources/views/admin/faq/index.blade.php
resources/views/admin/privacy/add.blade.php
resources/views/admin/privacy/edit.blade.php
resources/views/admin/privacy/index.blade.php
resources/views/admin/tac/add.blade.php
resources/views/layouts/app-admin-sidebar.blade.php
routes/admin.php

BC-185 [Task][Admin][Business] Frequent Ask Question (FAQ) DB

BC-185 [Task][Admin][Business] Page Frequent Ask Question (FAQ)  (List)

---

app/Http/Controllers/Admin/FaqController.php
app/Http/Controllers/Admin/PrivacyController.php
app/Models/Faq.php
database/migrations/2022_06_08_004222_create_faqs_table.php
resources/views/admin/faq/add.blade.php
resources/views/admin/faq/index.blade.php
resources/views/admin/privacy/add.blade.php
resources/views/admin/privacy/edit.blade.php
resources/views/admin/privacy/index.blade.php
resources/views/admin/tac/add.blade.php
resources/views/layouts/app-admin-sidebar.blade.php
routes/admin.php

BC-186 [Task][Admin][Business] Page Frequent Ask Question (FAQ)  (Add)

BC-186 [Task][Admin][Business] Page Frequent Ask Question (FAQ)  (Add)

---

app/Http/Controllers/Admin/FaqController.php
app/Http/Controllers/Admin/PrivacyController.php
app/Models/Faq.php
database/migrations/2022_06_08_004222_create_faqs_table.php
resources/views/admin/faq/add.blade.php
resources/views/admin/faq/edit.blade.php
resources/views/admin/faq/index.blade.php
resources/views/admin/privacy/add.blade.php
resources/views/admin/privacy/edit.blade.php
resources/views/admin/privacy/index.blade.php
resources/views/admin/tac/add.blade.php
resources/views/layouts/app-admin-sidebar.blade.php
routes/admin.php

BC-187 [Task][Admin][Business] Page Frequent Ask Question (FAQ)  (Edit)

BC-187 [Task][Admin][Business] Page Frequent Ask Question (FAQ)  (Edit)

---

app/Http/Controllers/Admin/FaqController.php
app/Http/Controllers/Admin/PrivacyController.php
app/Models/Faq.php
database/migrations/2022_06_08_004222_create_faqs_table.php
resources/views/admin/faq/add.blade.php
resources/views/admin/faq/edit.blade.php
resources/views/admin/faq/index.blade.php
resources/views/admin/privacy/add.blade.php
resources/views/admin/privacy/edit.blade.php
resources/views/admin/privacy/index.blade.php
resources/views/admin/tac/add.blade.php
resources/views/layouts/app-admin-sidebar.blade.php
routes/admin.php

BC-188 [Task][Admin][Business] Page Frequent Ask Question (FAQ)  (Delete)

BC-188 [Task][Admin][Business] Page Frequent Ask Question (FAQ)  (Delete)

---

app/Http/Controllers/Admin/FaqController.php
resources/views/admin/faq/add.blade.php
resources/views/admin/faq/edit.blade.php
resources/views/admin/faq/index.blade.php
resources/views/layouts/app-admin-sidebar.blade.php

BC-217 [Task][Admin][Business] Page Frequent Ask Question (FAQ) Improvement (Add/Edit)

BC-217 [Task][Admin][Business] Page Frequent Ask Question (FAQ) Improvement (Add/Edit)

---

app/Http/Controllers/Admin/FaqController.php
app/Models/General.php
database/migrations/2022_06_29_063626_create_generals_table.php
resources/views/admin/faq/add.blade.php
resources/views/admin/faq/edit.blade.php
resources/views/admin/faq/index.blade.php
resources/views/layouts/app-admin-sidebar.blade.php

BC-203 [Task][Admin][Business] General DB

BC-203 [Task][Admin][Business] General DB

---

app/Http/Controllers/Admin/GeneralController.php
resources/views/admin/general/index.blade.php
routes/admin.php
routes/merchant.php

improving general form for maintenance mode

improving general form for maintenance mode

---

app/Http/Controllers/Admin/OrderController.php
app/Http/Controllers/Admin/PaymentController.php
app/Http/Requests/OrderAdminRequest.php
resources/views/admin/orders/add.blade.php
resources/views/admin/orders/index.blade.php
routes/admin.php

Page Order Add/Create, Improve Integrated Payment Method with Master Payment BC-250

---

app/Http/Controllers/Merchant/Auth/LoginController.php
public/js/mapInput.js
resources/views/courier/auth/register.blade.php
resources/views/merchant/auth/register.blade.php

- all maps restritc indonesia only
- error validate with old input

BC-252 [Task][Merchant][Register] Improvement

---

.env.dev
app/Models/Merchant.php
resources/views/admin/merchant/index.blade.php

…loudinary (additional_image) BC-260

[Admin][Merchant] Improve Table List Merchant, Optimize Show Image Cloudinary (additional_image) BC-260

---

app/Http/Controllers/Admin/OrderController.php
database/migrations/2022_10_08_021310_change_type_price_to_products_table.php

dont forget composer install before run the migration

borneos-core bc-469

---

app/Http/Controllers/Admin/TravelController.php
resources/views/admin/travel/index.blade.php
routes/admin.php

- [BW-592] [Task][Admin][Travel] List, Action Send Ticket Travel with WA
- [BW-593] [Task][Admin][Travel] List, Pagination with active filter
- - [BW-591] [Task][Admin][Travel] List, Action Send Confirm KTP with WA

[BC-591] Improve Dashboard Travels
